import re

dic = {
	"AA" : "E",
	"AD" : "1",
	"AF" : "S",
	"AG" : "T",
	"AV" : "A",
	"AX" : "2",
	"DA" : "F",
	"DD" : "3",
	"DF" : "I",
	"DG" : "4",
	"DV" : "L",
	"DX" : "O",
	"FA" : "C",
	"FD" : "5",
	"FF" : "B",
	"FG" : "6",
	"FV" : "D",
	"FX" : "7",
	"GA" : "G",
	"GD" : "8",
	"GF" : "H",
	"GG" : "9",
	"GV" : "J",
	"GX" : "0",
	"VA" : "K",
	"VD" : "M",
	"VF" : "N",
	"VG" : "P",
	"VV" : "Q",
	"VX" : "R",
	"XA" : "U",
	"XD" : "V",
	"XF" : "W",
	"XG" : "X",
	"XV" : "Y",
	"XX" : "Z"
}

cripto = "AAXGDFAFAGAAXAVFAVGAVXAVVFFVDFXDAAVXAFDFFVAVFVFVAAVGAAVFDFFADFDVDFVFAVAFAFAGDXVGAVDVGAXAVFAVAFAAAFVGAAFADFAAAFFVAAGFDXVFGADXAFFVAADVGAAAVFAAVXDXVGAAVFDFFADFDVDVDFXAVDDVAVAFAFDFVFAGAAAGDFXXAVVFFVAADADXVXVDAVVFAVAGXAVXAVDVAFAGDXVGVFDXDXFFAFAGAVVFAGAAFVAAFFDFFVDXAVDVAVAVVGAVVXDFFADFDXVFFVAAVXAAAFDFAFAGAAVFFADFAVAFAFAAGFAVVFFVAAAFAVVXVXDXDVDVAVFVDXDXAGVXAVAFDAAVVDDFDVDFAVAFAFDFGAXADFAAVFFVDXFFAVAFDFFAAVVDAAVFAGAAFVDXAFAAAFAGVXAVAGAAGADFAVAFDVAVAVFVDFFADFDXVFFVAAGAVXXAVGDXAFAAVFDVAVFAAVFVAAVFAVDVAVAGAAVXAVDVFVAADVVGVXAAFAXAVXAFDXVXVGVXAAAFAAVFAGAAAAVFAADVVDAAFVDFDXFVAAFAXADVAGDFXDDXFVAADVGFDXVFGADXVGVXDXFVXAFAAGDXVXDXVDAAFVDFAVVFAGAADVAVVDDXFVDFDADFFAAVFADFDXVFVVXADFVDDFFAAVFVAADVAVVGAAVFDFFADFDVDFVFAVDXFFAGAAVFDFFVAVVGDXVXDAAAVXVDAAVFAGAVFADFDXVFFFDFDXAGAAFAVFDXDVDXGADFFAAVAAVFFV"
mensaje = ""


for c in re.findall("..", cripto):
	mensaje += dic.get(c)

print("Mensaje: {}".format(mensaje))